### ISSUE TITLE
Can you fix the Vulkan usage in a set of emulators?

### ISSUE THREAD

**Issue by Zero3K** [GpuZelenograd/memtest_vulkan#5]
One of the emulators in the set works for the most part (It just has black overlaying the game) while the other has an error when creating the compute pipeline. The source code for them can be found at https://sourceforge.net/projects/hpsx64/files/Source/v0410/hpsx64v0410.tar.xz/download.

**Comment by galkinvv** [comment]
Unfortunately I'm not the expert in graphics development - I specialize in graphics cards repair and the memtest_vulkan tool is my side project.


If you have some details about the "error while creating the compute pipeline" share it, maybe I can give some ideas if the problem would be similar to the problems I see during memtest_vulkan development.

However I'll definitely will NOT edit the code of those emulators myself - I've already have too much projects for now, to enter one more, hope for understanding

**Comment by Zero3K** [comment]
It might be an issue with the driver itself. I will see if the guy will send me the fix for the compute error in RE7 that he offered to other people a while ago and then see if it fixes this issue once I get and install it. If that doesn't fix it, then I will see what Intel finds regarding it.

**Comment by Zero3K** [comment]
Never mind, the fix for RE7 is a custom launcher.
